//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenLibrary.Data.ZeeRex
{
    using System;
    using System.Collections.Generic;
    
    public partial class authentication
    {
        public string required { get; set; }
        public string open { get; set; }
        public string user { get; set; }
        public string group { get; set; }
        public string password { get; set; }
    }
}
