//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenLibrary.Data.ZeeRex
{
    using System;
    using System.Collections.Generic;
    
    public partial class serverInfo
    {
        public string host { get; set; }
        public string port { get; set; }
        public string protocol { get; set; }
        public string version { get; set; }
        public string transport { get; set; }
        public string wsdl { get; set; }
    }
}
