// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 6.0.106.0. www.xsd2code.com
//    {"TargetFramework":"Net48","NameSpace":"OpenLibrary.Service","Properties":{},"XmlAttribute":{"Enabled":true},"ClassParams":{},"Miscellaneous":{}}
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace OpenLibrary.Service
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Runtime.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Xml;
    using System.Collections.Generic;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace = "http://docs.oasis-open.org/ns/search-ws/sruRequest")]
    [XmlRootAttribute("searchRetrieveRequest", Namespace = "http://docs.oasis-open.org/ns/search-ws/sruRequest", IsNullable = false)]
    public partial class searchRetrieveRequestType
    {
        #region Private fields
        private string _query;
        private string _startRecord;
        private string _maximumRecords;
        private recordXMLEscaping _recordXMLEscaping;
        private string _recordSchema;
        private string _resultSetTTL;
        private string _stylesheet;
        private string _queryType;
        private string _sortKeys;
        private renderedBy _renderedBy;
        private string _httpAccept;
        private string _responseType;
        private recordPacking _recordPacking;
        private string _facetLimit;
        private string _facetStart;
        private string _facetSort;
        private string _facetCount;
        private List<System.Xml.XmlElement> _any;
        #endregion

        public searchRetrieveRequestType()
        {
            _any = new List<System.Xml.XmlElement>();
            _startRecord = "1";
            _recordXMLEscaping = recordXMLEscaping.xml;
            _queryType = "cql";
            _renderedBy = renderedBy.client;
            _httpAccept = "application/soap+xml";
            _recordPacking = recordPacking.packed;
            _facetStart = "1";
        }

        public string query
        {
            get
            {
                return _query;
            }
            set
            {
                _query = value;
            }
        }

        [XmlElement(DataType = "positiveInteger")]
        public string startRecord
        {
            get
            {
                return _startRecord;
            }
            set
            {
                _startRecord = value;
            }
        }

        [XmlElement(DataType = "nonNegativeInteger")]
        public string maximumRecords
        {
            get
            {
                return _maximumRecords;
            }
            set
            {
                _maximumRecords = value;
            }
        }

        public recordXMLEscaping recordXMLEscaping
        {
            get
            {
                return _recordXMLEscaping;
            }
            set
            {
                _recordXMLEscaping = value;
            }
        }

        public string recordSchema
        {
            get
            {
                return _recordSchema;
            }
            set
            {
                _recordSchema = value;
            }
        }

        [XmlElement(DataType = "nonNegativeInteger")]
        public string resultSetTTL
        {
            get
            {
                return _resultSetTTL;
            }
            set
            {
                _resultSetTTL = value;
            }
        }

        [XmlElement(DataType = "anyURI")]
        public string Stylesheet
        {
            get
            {
                return _stylesheet;
            }
            set
            {
                _stylesheet = value;
            }
        }

        public string queryType
        {
            get
            {
                return _queryType;
            }
            set
            {
                _queryType = value;
            }
        }

        public string sortKeys
        {
            get
            {
                return _sortKeys;
            }
            set
            {
                _sortKeys = value;
            }
        }

        public renderedBy renderedBy
        {
            get
            {
                return _renderedBy;
            }
            set
            {
                _renderedBy = value;
            }
        }

        public string httpAccept
        {
            get
            {
                return _httpAccept;
            }
            set
            {
                _httpAccept = value;
            }
        }

        public string responseType
        {
            get
            {
                return _responseType;
            }
            set
            {
                _responseType = value;
            }
        }

        public recordPacking recordPacking
        {
            get
            {
                return _recordPacking;
            }
            set
            {
                _recordPacking = value;
            }
        }

        public string facetLimit
        {
            get
            {
                return _facetLimit;
            }
            set
            {
                _facetLimit = value;
            }
        }

        [XmlElement(DataType = "positiveInteger")]
        public string facetStart
        {
            get
            {
                return _facetStart;
            }
            set
            {
                _facetStart = value;
            }
        }

        public string facetSort
        {
            get
            {
                return _facetSort;
            }
            set
            {
                _facetSort = value;
            }
        }

        public string facetCount
        {
            get
            {
                return _facetCount;
            }
            set
            {
                _facetCount = value;
            }
        }

        [XmlAnyElementAttribute()]
        public List<System.Xml.XmlElement> Any
        {
            get
            {
                return _any;
            }
            set
            {
                _any = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [Serializable]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://docs.oasis-open.org/ns/search-ws/sruRequest")]
    [XmlRootAttribute(Namespace = "http://docs.oasis-open.org/ns/search-ws/sruRequest", IsNullable = false)]
    public enum recordXMLEscaping
    {
        xml,
        @string,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [Serializable]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://docs.oasis-open.org/ns/search-ws/sruRequest")]
    [XmlRootAttribute(Namespace = "http://docs.oasis-open.org/ns/search-ws/sruRequest", IsNullable = false)]
    public enum renderedBy
    {
        client,
        server,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [Serializable]
    [XmlTypeAttribute(AnonymousType = true, Namespace = "http://docs.oasis-open.org/ns/search-ws/sruRequest")]
    [XmlRootAttribute(Namespace = "http://docs.oasis-open.org/ns/search-ws/sruRequest", IsNullable = false)]
    public enum recordPacking
    {
        packed,
        unpacked,
    }
}
#pragma warning restore
