//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenLibrary.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OpenLibraryEntities : DbContext
    {
        public OpenLibraryEntities()
            : base("name=OpenLibraryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Library> Libraries { get; set; }
        public virtual DbSet<Sitemap> Sitemaps { get; set; }
        public virtual DbSet<WebService> WebServices { get; set; }
        public virtual DbSet<WebServiceEndpoint> WebServiceEndpoints { get; set; }
        public virtual DbSet<WebServiceEndpointTaskEvent> WebServiceEndpointTaskEvents { get; set; }
        public virtual DbSet<WebServiceEndpointUrlRequestTask> WebServiceEndpointUrlRequestTasks { get; set; }
        public virtual DbSet<WebServiceParameter> WebServiceParameters { get; set; }
        public virtual DbSet<WebServiceParameterSetting> WebServiceParameterSettings { get; set; }
    }
}
