//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebService
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WebService()
        {
            this.WebServiceEndpoints = new HashSet<WebServiceEndpoint>();
            this.WebServiceParameters = new HashSet<WebServiceParameter>();
        }
    
        public int Id { get; set; }
        public string LibraryName { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string System { get; set; }
        public string Subsystem { get; set; }
        public string ReferenceUrl { get; set; }
    
        public virtual Library Library { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebServiceEndpoint> WebServiceEndpoints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebServiceParameter> WebServiceParameters { get; set; }
    }
}
