//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebServiceEndpointUrlRequestTask
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WebServiceEndpointUrlRequestTask()
        {
            this.WebServiceEndpointTaskEvents = new HashSet<WebServiceEndpointTaskEvent>();
        }
    
        public int Id { get; set; }
        public int WebServiceEndpointId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Host { get; set; }
        public string Method { get; set; }
        public int TimeoutMilliseconds { get; set; }
        public string RequestUrl { get; set; }
        public bool RequestUrlTokenized { get; set; }
    
        public virtual WebServiceEndpoint WebServiceEndpoint { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebServiceEndpointTaskEvent> WebServiceEndpointTaskEvents { get; set; }
    }
}
