//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebServiceParameter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WebServiceParameter()
        {
            this.WebServiceParameter1 = new HashSet<WebServiceParameter>();
            this.WebServiceParameterSettings = new HashSet<WebServiceParameterSetting>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ParentId { get; set; }
        public int WebServiceId { get; set; }
        public string Name { get; set; }
        public string DefaultValue { get; set; }
        public bool DefaultSearchField { get; set; }
        public bool Required { get; set; }
        public bool CommaDelimited { get; set; }
        public bool ArrayParameter { get; set; }
        public string Description { get; set; }
    
        public virtual WebService WebService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebServiceParameter> WebServiceParameter1 { get; set; }
        public virtual WebServiceParameter WebServiceParameter2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebServiceParameterSetting> WebServiceParameterSettings { get; set; }
    }
}
