//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebServiceParameterSetting
    {
        public int Id { get; set; }
        public int WebServiceParameterId { get; set; }
        public string PossibleValue { get; set; }
        public string Explanation { get; set; }
    
        public virtual WebServiceParameter WebServiceParameter { get; set; }
    }
}
