//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebServiceEndpoint
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WebServiceEndpoint()
        {
            this.WebServiceEndpointUrlRequestTasks = new HashSet<WebServiceEndpointUrlRequestTask>();
            this.WebServiceParameters = new HashSet<WebServiceParameter>();
        }
    
        public int Id { get; set; }
        public int WebServiceId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Endpoint { get; set; }
        public string ReferenceUrl { get; set; }
        public bool SSLRequired { get; set; }
    
        public virtual WebService WebService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebServiceEndpointUrlRequestTask> WebServiceEndpointUrlRequestTasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebServiceParameter> WebServiceParameters { get; set; }
    }
}
