//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenLibrary.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebServiceEndpoint
    {
        public int Id { get; set; }
        public int WebServiceId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Endpoint { get; set; }
        public string ReferenceUrl { get; set; }
        public bool SSLRequired { get; set; }
    
        public virtual WebService WebService { get; set; }
    }
}
